### ISSUE TITLE
Should stop sending AdGuard server

### ISSUE THREAD

**Issue by haunt98** [Visafe/VisafeIOS#1]
As according to this https://twitter.com/ay_meshkov/status/1453773972747718659:

This app is sending request to AdGuard server, I know this app and AdGuard is both GPLv3 but I think this app should use a dedicated server for checking request, not using AdGuard server for this.

**Comment by htruong** [comment]
I think the developers should lock this issue until it cools down. 

There have been too many comments violating the [Github Community Guidelines](https://docs.github.com/articles/github-community-guidelines) for being off-topic and abusive and not respectful. I'd rather not having to deal with the mob with new accounts and angry comments about this project.

**Comment by nkoc6a15** [comment]
> I think the developers should lock this issue until it cools down.
> 
> There have been too many comments violating the [Github Community Guidelines](https://docs.github.com/articles/github-community-guidelines) for being off-topic and abusive and not respectful. I'd rather not having to deal with the mob with new accounts and angry comments about this project.

Dont blame us my fen. 5 years and they give us Adguard iOS reskin. We are not abuse, we are telling the truth so they can fix and hopefully they wont make any mistake in the future. 💁‍♂️

**Comment by luxysiv** [comment]
> just don't install this app. HieuPC is brainwashing people that he's some kind of superior hacker but actually he's just a script kid and no one should praise a person who once in jail and doesn't do any honest thing

I call him HiếuBuff, now is HiếuBoobs

**Comment by luxysiv** [comment]
> @tohruniverse
> 
> Tôi nghĩ là riêng việc họ nội địa hóa để cho người dân bình thường (trong đó có bố mẹ tôi) dùng được những tính năng chống spam, chống quảng cáo, thay vì phải dùng Adguard mà họ không quen cũng là một việc tốt, mang lại sự tích cực trong xã hội rồi.. Nếu như đó là điều duy nhất họ làm được bây giờ thì cũng là đáng quý rồi. Việc họ có làm được thêm nhiều tính năng khác có ý nghĩa hay không, nhiều hay ít sẽ cần thời gian và nhiều người để đánh giá. Hãy cho họ thời gian.
> 
> Tôi nghĩ chúng ta thay vì biến github thành facebook để tấn công cá nhân hay nêu quan điểm chính trị thì hãy trở lại chủ đề chính. Việc tác giả yêu cầu đừng dùng Adguard mới chưa được 1 hôm. Tôi thấy họ có lắng nghe ý kiến của mọi người và thay đổi repository của mình để credit tác giả (nếu họ không nhận sai bạn cũng không làm gì được phải không?). Họ cũng rất cởi mở xin lỗi tác giả vì dùng server của tác giả rồi (mặc dù nếu họ thật sự không muốn cộng tác thì họ không cần xin lỗi). Và họ cũng làm đúng luật GPLv3.
> 
> Đây là lần đầu tiên tôi thấy một dự án lắng nghe mọi người và tôn trọng tác quyền tác giả như vậy, mặc dù họ có thiếu sót bước đầu. Như vậy là họ đi đúng hướng. Bạn có thấy dự án BlueZone lắng nghe bất cứ ai như vậy không? Kinh nghiệm của tôi mở issue trên github của BlueZone là họ không hề có phản hồi cũng không sửa chữa gì cả.
> 
> Cá nhân tôi cho những người phát triển visafe này benefits of the doubt khi chúng ta có nghi ngờ. Lý do chúng ta cần phải ủng hộ thay vì đi ném đá những người như vậy để mong rằng nhiều người trong chính phủ sẽ thấy sự tích cực trong việc phát triển mở như thế này. Cái dở nhất là họ bực và sợ những câu tấn công lên án đề sau không dự án nào của chính phủ dám làm gì mở trên github này nữa. Nếu mình chỉ muốn lên án họ cho sướng mồm bằng nick của mình thì hệ quả này về sau người khổ chỉ sẽ là người dân như tôi và các bạn và con cháu của chúng ta thôi. Tôi không thích gì sự làm ăn vớ vẩn của nhiều dự án, nhưng cái gì có triển vọng là sẽ đúng thì tôi nghĩ chúng ta nên khuyến khích để họ tiếp tục đi đúng dần từng bước.

Mang tiếng dân công nghệ mà không biết set up AdGuard cho bố mẹ bạn thì bạn nên …..

**Comment by danglequocbao001** [comment]
> @htruong Tôi respect bạn sau khi xem qua những gì bạn đã đóng góp trên blog, nhưng trong trường hợp này tôi ko thấy lí do nên bênh thằng Visafe này ở đâu cả. Điều mà tôi cay nhất thằng này đó là nó ngốn nhiều tiền, gáy to mà cái ruột chẳng cần có tí chất xám nào. Bạn xem đó, nếu như tìm kiếm Google trên các báo VN viết thì toàn từ ngữ đao to búa lớn, đa nền tảng, Trung tâm Giám sát an toàn không gian mạng quốc gia, Cục An toàn thông tin (Bộ TT&TT), Tổng công ty Truyền thông đa phương tiện.... mà nghe thôi tôi đã tưởng tượng ra 1 data center xịn sò nơi mà cả trăm dàn máy core i9-9900k + RTX 2080 đang chạy suốt ngày đêm để cho ra 1 sản phẩm gắn mác "Trí tuệ Việt Nam". Ôi tự hào ko? Ngạo nghễ quá đi chứ. Cho đến khi anh CTO AdGuard anh ý tweet. Tôi sẽ viết lại ở đây dưới góc nhìn 1 dòng thời gian khác, khi anh ấy sử dụng tiếng Việt nhé.
> 
> * App của bọn tao là Open Source, đôi khi bọn tao thấy mấy cái app khác nó giống y hệt được publish, nhưng chúng tao cũng mặc kệ, không đáng quan tâm. Nhưng hôm nay tao chịu hết nổi rồi, thằng Visafe nó copy láo quá. Nhìn cái repo này mà xem, rõ ràng 100% là code của tao. Thế mà thằng nào sinh năm 99 lại ghi "first commit" thế này? Ôi vãi l bạn ạ nó ko fork mà nó clone nguyên về, xóa git log đi rồi push lên 1 remote khác. Thôi tao xin thua. Mày làm gì kệ, a nhưng còn gì nữa? Mày request đến server của tao à? Trời ơi giả sử bọn mày bắt người dân nhà nhà cài Visafe thêm mấy chục triệu request nữa chạy qua chắc bắt tao bỏ tiền túi mua thêm phần cứng + máy ảo để phục vụ chúng mày. Có khác gì thằng ăn trộm đi vào nhà còn bắt chủ nhà mở tủ lạnh điều hòa bật chai rượu vang 50 năm ra mời nó uống? Thôi thà nó là thằng dev ất ơ vô danh tao cũng ko chấp, nhưng đằng sau nó là "Goverment" đó ạ. Tao chịu thua, làm dev thì thằng nào chả đi copy stackoverflow nhưng chúng mày copy ngu quá, copy không có chọn lọc. Copy đến nỗi biến server của bọn tao thành 1 con worker cho bọn mày. Khổ ghê, nhưng mà bọn tao có được credit gì đâu, trên AppStore cái ứng dụng 50MB của bọn mày build đến 99% code tao mà còn không có 1 dòng "phát triển dựa trên AdGuard". Cảm thấy công sức của tao và team trong suốt ngần ấy năm bị ăn cắp 1 cách trắng trợn. Giả sử chúng mày fork, credit tao, có bug/issue gì chúng mày báo tao để cả 2 cùng fix thì tao sẵn sàng ô kê, thế mới là tinh thần open source, nhưng chúng mày copy thế này thì quá đáng lắm thiếu nước ngồi lên đầu tao.
> 
> Bạn thấy đó, ngay trên repo của AdGuard cũng đã hướng dẫn build chi tiết đến tận răng rồi, việc còn lại chỉ là localize sang tiếng Việt, chỗ nào background xanh ta chỉnh màu đỏ cho yêu nước, checkbox hình vuông ta cho border-radius chỉnh thành hình tròn cho khác đi 1 tí, thay đổi filter by word của họ là "f**k, sh*t" thì ta thay bằng "vl, vkl, dcmm", if domain.meta.description.contains("tín dụng, cờ bạc,...") then blackList.push(domain)...., và điều cản trở tôi không publish lên AppStore 1 bản Visafe-69420 là do tôi ko có account Apple Developers.
> 
> Team Visafe nếu có dùng tiền thuế của tôi để dev app này thì tôi khuyên nên đấm tiền cho anh CTO AdGuard xóa bài, coi như đây là 1 bài học lần sau sandbox run scenario đầy đủ rồi hãy go live. Anh này là tay to trong lĩnh vực công nghệ, Cái extension trên Chrome của anh ý có đến hơn 10 triệu lượt tải về rồi. Giả sử như có 1 anh Tây entrepreneur đang cần thuê outsource, hỏi anh này ý kiến "Tao đang có 1 project ngon tiềm năng lắm, muốn thuê dev mấy nước châu Á làm mà chưa chọn được ai, mày tư vấn được không" anh ý lại trả lời là "Thuê ai thì thuê nhưng tao nhớ trước có mấy thằng Việt Nam copy nguyên source code của tao rồi nhận là của nó, còn không đổi URL trong environment nữa " - là hỏng.
> 
> For non-Vietnamese speaker - just Google translate or TLDR - I explained Andrey Meshkov though from my point of view. And in conclusion, Visafe is just a cheap clone app from AdGuard, but they used media to broadcast themselves as a production software made by Vietnamese people.

Nice commit, also a pull request =))

**Comment by paulofdune1951** [comment]
You know, I thought Warcraft Reforged was the worst rip-off ever, but at least Blizz reused their own stuff. Unlike this one...

**Comment by AlphaNecron** [comment]
> You know, I thought Warcraft Reforged was the worst rip-off ever, but at least Blizz reused their own stuff. Unlike this one...

This is a governmental project, with a lot of budget, ripping-off a famous project entirely is unacceptable. So disappointed.

**Comment by nkoc6a15** [comment]
> Mang tiếng dân công nghệ mà không biết set up AdGuard cho bố mẹ bạn thì bạn nên …..

Đúng thật. Tính ra do giới hạn của iOS nên Adguard iOS nó lược bớt tính năng nhiều lắm rồi ấy mà bạn ấy không biết setup cho người nhà nữa thì chịu luôn :))) chứ qua Android dùng Adguard + InviZible NextDNS DoH + PowerTunnel qua Proxy để bypass internet censorship nữa kìa.

**Comment by QuanTrieuPCYT** [comment]
agreed, and yet so disappointed as this is a governmental project and the dev just blatantly ripoff the code
*man*

**Comment by nkoc6a15** [comment]
Not good. Adguard EN group in Telegram pined a message talk about this scandal

**Comment by tuetranduy** [comment]
> I think the developers should lock this issue until it cools down.
> 
> There have been too many comments violating the [Github Community Guidelines](https://docs.github.com/articles/github-community-guidelines) for being off-topic and abusive and not respectful. I'd rather not having to deal with the mob with new accounts and angry comments about this project.

đúng kiểu không cãi lại được thì chặn họng, VN không phát triển được là vì có thằng tư duy như bạn đấy.

**Comment by tientmse62290** [comment]
> just don't install this app. HieuPC is brainwashing people that he's some kind of superior hacker but actually he's just a script kid and no one should praise a person who once in jail and doesn't do any honest thing

just let you know that he is not a script kiddie because no script kiddie can archive OSWE

**Comment by aperture147** [comment]
> @aperture147 @minhhoang8bit @nkoc6a15 @nautiam @AlphaNecron please refrain from making ad-hominem comments that have nothing to do with the issue. It is not clear what Visafe did wrong here, the fact that Visafe the app is using adguard servers does not, by itself, violate any ethical standards I am aware of.
> 
> Visafe is respecting GPLv3 and crediting the original project. The fact that you're seeing them publishing the source code is commendable. The fact that the original project author does not like the way this project behaves does not mean what Visafe is doing is wrong. In fact, that is the utmost important right that the GPLv3 license provides to us: The original authors do not have to like what the forks of the projects do.
> 
> Please stop the witch hunt and fuel the flame.
> 
> I know hieupc personally, but I am no way defending him or visafe or NCSC of any wrongdoing. I am speaking as a long time advocate of free software and author of several GPLv3 software projects myself.

Yeah you can rip off their program and say that it’s all yours and it doesn’t violate the GPLv3 license, but you have also destroy your honesty and thrown dirt into the OpenSource community. You previously said this project takes 5 years to make and costs a lot of thoughts, but actually this is just a rebranded software with not much modification in its core. You are also trying to hide your deception buy force push to overwrite the branch, switch the main branch to hide the truth that you don’t want people to find out that you are not the real author of this software. I’m so disappointed that a gorvernment project is actually a rip off of a Russian software and they don’t even try to prevent that app to send the data back to Russia. I have nothing to say, you are not just a theft, you are also stupid.

**Comment by truong-bui** [comment]
> 
> 
> @tohruniverse
> 
> Tôi nghĩ là riêng việc họ nội địa hóa để cho người dân bình thường (trong đó có bố mẹ tôi) dùng được những tính năng chống spam, chống quảng cáo, thay vì phải dùng Adguard mà họ không quen cũng là một việc tốt, mang lại sự tích cực trong xã hội rồi.. Nếu như đó là điều duy nhất họ làm được bây giờ thì cũng là đáng quý rồi. Việc họ có làm được thêm nhiều tính năng khác có ý nghĩa hay không, nhiều hay ít sẽ cần thời gian và nhiều người để đánh giá. Hãy cho họ thời gian.
> 
#### Ngụy biện. Nội địa hóa bằng cách lấy sản phẩm của người khác, sửa tên, sửa giao diện rồi nhận là mình làm gọi là nội địa hóa???

> Tôi nghĩ chúng ta thay vì biến github thành facebook để tấn công cá nhân hay nêu quan điểm chính trị thì hãy trở lại chủ đề chính. Việc tác giả yêu cầu đừng dùng Adguard mới chưa được 1 hôm. Tôi thấy họ có lắng nghe ý kiến của mọi người và thay đổi repository của mình để credit tác giả (nếu họ không nhận sai bạn cũng không làm gì được phải không?). Họ cũng rất cởi mở xin lỗi tác giả vì dùng server của tác giả rồi (mặc dù nếu họ thật sự không muốn cộng tác thì họ không cần xin lỗi). Và họ cũng làm đúng luật GPLv3.> 
>
#### Lấp liếm cái sai. Ăn cắp xong bị bắt quả tang mới bắt đầu xin lỗi, nếu ông CTO Adguard mà ko nói gì tôi cá bọn nó cứ vô tư nhận vơ công sức của người khác. Mẹ cái bọn chuyên ăn cắp sản phẩm của người khác rồi nhận là của mình làm tôi lạ đéo gì, đi làm ở công ty nào cũng gặp cái dạng này, nhất là ở mấy công ty outsourcing hay môi trường nhà nước.

> Đây là lần đầu tiên tôi thấy một dự án lắng nghe mọi người và tôn trọng tác quyền tác giả như vậy, mặc dù họ có thiếu sót bước đầu. Như vậy là họ đi đúng hướng. Bạn có thấy dự án BlueZone lắng nghe bất cứ ai như vậy không? Kinh nghiệm của tôi mở issue trên github của BlueZone là họ không hề có phản hồi cũng không sửa chữa gì cả.
> 
#### Lần đầu tiên??? =)))) Thôi thôi anh ơi, bợ đít nghe mắc ỉa. Nghe như mấy em gái dẩm ngủ với cả trăm thằng mà với anh nào cũng bô bô đây là lần đầu của em =)))) 
#### Lắng nghe mọi người và tôn trọng quyển tác giả??? Chứ không phải do bị bóc phốt xong mới bắt đầu tìm cách lấp liếm cái sai à?

> Cá nhân tôi cho những người phát triển visafe này benefits of the doubt khi chúng ta có nghi ngờ. Lý do chúng ta cần phải ủng hộ thay vì đi ném đá những người như vậy để mong rằng nhiều người trong chính phủ sẽ thấy sự tích cực trong việc phát triển mở như thế này. Cái dở nhất là họ bực và sợ những câu tấn công lên án đề sau không dự án nào của chính phủ dám làm gì mở trên github này nữa. Nếu mình chỉ muốn lên án họ cho sướng mồm bằng nick của mình thì hệ quả này về sau người khổ chỉ sẽ là người dân như tôi và các bạn và con cháu của chúng ta thôi. Tôi không thích gì sự làm ăn vớ vẩn của nhiều dự án, nhưng cái gì có triển vọng là sẽ đúng thì tôi nghĩ chúng ta nên khuyến khích để họ tiếp tục đi đúng dần từng bước.
>
#### Việc phát triển mã nguồn mở là điều đáng khuyến khích, cũng giống như việc ăn cắp sản phẩm của người khác rồi nhận là của mình là việc đáng bị lên án. Ăn cắp trót lọt 1 lần sẽ có lần thứ 2, thứ 3, lâu dài sẽ thành bản chất đéo sửa được. Việc bọn ăn cắp ăn trộm bị lên án, bị đấu tố thì cũng xứng đáng với hành động của nó. Nếu không có người lên án, tôi tin bọn nó sẽ vẫn tiếp tục ngựa quen đường cũ và làm gương xấu cho thế hệ tiếp theo. Dám chơi dám chịu thôi, đã có gan ăn cắp thì nên có gan chấp nhận hậu quả.

**Comment by Long-FA** [comment]
![Untitled](https://user-images.githubusercontent.com/73825967/139572526-62499bd9-2e1d-4a3b-9ecb-96a20b780a58.png)

**Comment by paulofdune1951** [comment]
> > I think the developers should lock this issue until it cools down.
> > There have been too many comments violating the [Github Community Guidelines](https://docs.github.com/articles/github-community-guidelines) for being off-topic and abusive and not respectful. I'd rather not having to deal with the mob with new accounts and angry comments about this project.
> 
> đúng kiểu không cãi lại được thì chặn họng, VN không phát triển được là vì có thằng tư duy như bạn đấy.

may mà tác giả adguard ko phải người ở vn, chứ không thì chắc không yên rồi

**Comment by luxysiv** [comment]
> @aperture147 @minhhoang8bit @nkoc6a15 @nautiam @AlphaNecron please refrain from making ad-hominem comments that have nothing to do with the issue. It is not clear what Visafe did wrong here, the fact that Visafe the app is using adguard servers does not, by itself, violate any ethical standards I am aware of.
> 
> Visafe is respecting GPLv3 and crediting the original project. The fact that you're seeing them publishing the source code is commendable. The fact that the original project author does not like the way this project behaves does not mean what Visafe is doing is wrong. In fact, that is the utmost important right that the GPLv3 license provides to us: The original authors do not have to like what the forks of the projects do.
> 
> Please stop the witch hunt and fuel the flame.
> 
> I know hieupc personally, but I am no way defending him or visafe or NCSC of any wrongdoing. I am speaking as a long time advocate of free software and author of several GPLv3 software projects myself.

@htruong tôi nói thẳng ra là ăn cắp. copy ngu tới độ còn không biết xoá request unlock premium bên iOS khi pack app lại. Tôi không biết nó có “xài” server chùa không nhưng trước khi CTO AdGuard tweet, mấy người trong nhóm tôi đã phát hiện là ăn cắp của AdGuard chỉ thêm cái logo thôi. Còn nữa, cái chúng tôi phát hiện là visafe gửi request unlock premium của server AdGuard. Cười sặc máu. Thấy người ta tweet mới DM xin lỗi rồi sửa thêm. :) cho tôi cười thẳng vào mặt bạn cái

**Comment by aperture147** [comment]
> > @aperture147 @minhhoang8bit @nkoc6a15 @nautiam @AlphaNecron please refrain from making ad-hominem comments that have nothing to do with the issue. It is not clear what Visafe did wrong here, the fact that Visafe the app is using adguard servers does not, by itself, violate any ethical standards I am aware of.
> > Visafe is respecting GPLv3 and crediting the original project. The fact that you're seeing them publishing the source code is commendable. The fact that the original project author does not like the way this project behaves does not mean what Visafe is doing is wrong. In fact, that is the utmost important right that the GPLv3 license provides to us: The original authors do not have to like what the forks of the projects do.
> > Please stop the witch hunt and fuel the flame.
> > I know hieupc personally, but I am no way defending him or visafe or NCSC of any wrongdoing. I am speaking as a long time advocate of free software and author of several GPLv3 software projects myself.
> 
> @htruong tôi nói thẳng ra là ăn cắp. copy ngu tới độ còn không biết xoá request unlock premium bên iOS khi pack app lại. Tôi không biết nó có “xài” server chùa không nhưng trước khi CTO AdGuard tweet, mấy người trong nhóm tôi đã phát hiện là ăn cắp của AdGuard chỉ thêm cái logo thôi. Còn nữa, cái chúng tôi phát hiện là visafe gửi request unlock premium của server AdGuard. Cười sặc máu. Thấy người ta tweet mới DM xin lỗi rồi sửa thêm. :) cho tôi cười thẳng vào mặt bạn cái

CTO của AdGuard đăng bài 13 tiếng trước, trong khi first commit lại là 9 tiếng trước. Rõ rằng là ghi đè branch và xoá dấu vết, chứ nếu để commit cũ thì lộ ngay ra là lấy source của người ta xong nói là của mình. Tất nhiên GPLv3 không ngăn chặn việc lấy đồ người khác xong bảo là của mình, nhưng như thế thì đúng là ném phân vào cộng đồng Open Source.

**Comment by luxysiv** [comment]
> > > @aperture147 @minhhoang8bit @nkoc6a15 @nautiam @AlphaNecron please refrain from making ad-hominem comments that have nothing to do with the issue. It is not clear what Visafe did wrong here, the fact that Visafe the app is using adguard servers does not, by itself, violate any ethical standards I am aware of.
> > > Visafe is respecting GPLv3 and crediting the original project. The fact that you're seeing them publishing the source code is commendable. The fact that the original project author does not like the way this project behaves does not mean what Visafe is doing is wrong. In fact, that is the utmost important right that the GPLv3 license provides to us: The original authors do not have to like what the forks of the projects do.
> > > Please stop the witch hunt and fuel the flame.
> > > I know hieupc personally, but I am no way defending him or visafe or NCSC of any wrongdoing. I am speaking as a long time advocate of free software and author of several GPLv3 software projects myself.
> > 
> > 
> > @htruong tôi nói thẳng ra là ăn cắp. copy ngu tới độ còn không biết xoá request unlock premium bên iOS khi pack app lại. Tôi không biết nó có “xài” server chùa không nhưng trước khi CTO AdGuard tweet, mấy người trong nhóm tôi đã phát hiện là ăn cắp của AdGuard chỉ thêm cái logo thôi. Còn nữa, cái chúng tôi phát hiện là visafe gửi request unlock premium của server AdGuard. Cười sặc máu. Thấy người ta tweet mới DM xin lỗi rồi sửa thêm. :) cho tôi cười thẳng vào mặt bạn cái
> 
> CTO của AdGuard đăng bài 13 tiếng trước, trong khi first commit lại là 9 tiếng trước. Rõ rằng là ghi đè branch và xoá dấu vết, chứ nếu để commit cũ thì lộ ngay ra là lấy source của người ta xong nói là của mình. Tất nhiên GPLv3 không ngăn chặn việc lấy đồ người khác xong bảo là của mình, nhưng như thế thì đúng là ném phân vào cộng đồng Open Source.

Tâm huyết 5 năm đấy! Kaka

**Comment by duongaanh** [comment]
top 10 anime betrayals

**Comment by EndermanHackerVN** [comment]
> Tâm huyết 5 năm đấy! Kaka. Ông CTO cũng biết status tâm huyết và buổi ra mắt luôn

@luxysiv may là ông CTO status ngay ngày đầu bốc phốt chứ để đợi mấy tháng rồi chèn cái logger vào máy mình thì....

**Comment by ethanduong** [comment]
Nói tóm lại là tôi thấy cái vụ này bị chửi lắm là bởi vì

- Góc nhìn của người dân đóng thuế: Đớp bao nhiêu tiền của dân xong lên báo đài nổ ầm ầm xong tòi ra là clone nguyên cái app về chỉnh sửa tí xíu =)) cái đấy thì sinh viên cũng làm được mà có khi còn làm free luôn ấy
- Góc nhìn của 1 người VN: Làm ăn vớ vẩn đến độ bị bọn tác giả call out trên Twitter =)) xấu hổ vl
- Góc nhìn của 1 lập trình viên: Trình độ đến đâu mà cái URL cũng không sửa lại để nó call vào server gốc =))))

**Comment by luxysiv** [comment]
> > Tâm huyết 5 năm đấy! Kaka. Ông CTO cũng biết status tâm huyết và buổi ra mắt luôn
> 
> @luxysiv may là ông CTO status ngay ngày đầu bốc phốt chứ để đợi mấy tháng rồi đội 99 chèn cái logger vào máy mình thì....

@EndermanHackerVN  tính cho nó 1 sao cơ mà thằng Apple bắt tải app mới đánh giá được. Quyết định không tải cho đỡ bẩn tài khoản.

**Comment by 9xcoder** [comment]
> Nói tóm lại là tôi thấy cái vụ này bị chửi lắm là bởi vì
> 
> * Góc nhìn của người dân đóng thuế: Đớp bao nhiêu tiền của dân xong lên báo đài nổ ầm ầm xong tòi ra là clone nguyên cái app về chỉnh sửa tí xíu =)) cái đấy thì sinh viên cũng làm được mà có khi còn làm free luôn ấy
> * Góc nhìn của 1 người VN: Làm ăn vớ vẩn đến độ bị bọn tác giả call out trên Twitter =)) xấu hổ vl
> * Góc nhìn của 1 lập trình viên: Trình độ đến đâu mà cái URL cũng không sửa lại để nó call vào server gốc =))))

Người ta có share code backend đâu mà chẳng phải trỏ vào đấy, build xong cái backend thì chắc quá deadline rồi nên phải làm ăn bố láo.

**Comment by icy** [comment]
fyi, I executed a diff command , to see changes between the two products. You may see tne diff here

https://gist.github.com/icy/b58d621638559f68c9ec4709e215c1f1#

I'd suggest the team to re-add the Acknowledgments section 

https://gist.github.com/icy/b58d621638559f68c9ec4709e215c1f1#file-visafeios-diff-L829

"ăn quả nhớ kẻ trồng cây" it's already said.

Have great time annd I do wish your product the best.

**Comment by vinhtn281990** [comment]
![1635605112356](https://user-images.githubusercontent.com/54103727/139643958-cfcbc08a-71a4-4698-a966-a40e14f46960.png)
họ chỉ muốn quốc hữu hóa "Tây Lông" product thôi mà =))

**Comment by danglequocbao001** [comment]
hơi tham =))
![image](https://user-images.githubusercontent.com/56766274/139676375-708e82e0-2d2a-4d62-bf30-cc0926817adf.png)
