### ISSUE TITLE
Will you guys public filter list and more information about your server?

### ISSUE THREAD

**Issue by nkoc6a15** [Visafe/VisafeIOS#4]
I mentioned in your facebook post but i dont see any reply. Will you guys upload a filter list uses to block malware, ads, trackings, etc..? 

And about your server? Will it keeps any logs? I afraid when i visit bbc vietnam the police will arrest me :( because they think me 3que

**Comment by VisafeTeam** [comment]
Hi @nkoc6a15, the filter lists of Visafe, which are close-source, will not be published. You can find more information about Visafe at https://docs.visafe.vn.
