### ISSUE TITLE
Cool skid!

### ISSUE THREAD

**Issue by EndermanHackerVN** [Visafe/VisafeIOS#7]
Really appreciate how you guys can skid Adguard and forgot to change the API server IP! 👍 

And also, maybe NCSC is too new to github that they don't know how to fork the project, instead of cloning and remake an even shitter GUI, then upload it to github without the commit history! Probally not to skid and completely rip-off adguard? Right? Vietnamese government did this!1!1! How can they skid soft wear!11!

And to add more fuel to the fire, they don't even credit the Adguard team in the readme. 🤣 
[twitter post from co-founder of adguard](https://twitter.com/ay_meshkov/status/1453773972747718659
) and also they blatantly send their logged info from their clients to adguard's server!1! 🤡

**Comment by AlphaNecron** [comment]
> Really appreciate how you guys can skid Adguard and forgot to change the API server IP! 👍
> 
> And also, maybe NCSC is too new to github that they don't know how to fork the project, instead of cloning and remake an even shitter GUI, then upload it to github without the commit history! Probally not to skid and completely rip-off adguard? Right? Vietnamese government did this!1!1! How can they skid soft wear!11!
> 
> And to add more fuel to the fire, they don't even credit the Adguard team in the readme. 🤣 [twitter post from co-founder of adguard](https://twitter.com/ay_meshkov/status/1453773972747718659) and also they blatantly send their logged info from their clients to adguard's server!1! 🤡

"Experienced and professional developers", and they don't know how to use GitHub? Ironically.

**Comment by QuanTrieuPCYT** [comment]
waiting for your replies...

**Comment by EndermanHackerVN** [comment]
bet Visafe will close this thread soon 👀

**Comment by QuanTrieuPCYT** [comment]
same thought, welp let's just wait kkk

**Comment by veeeleven** [comment]
I bet a lot of countries will say to our country: "The Vietnamese Developers don't know anything."

**Comment by EndermanHackerVN** [comment]
we are vietnamese @veeeleven

**Comment by nkoc6a15** [comment]
Not good. Adguard EN group in Telegram pin a message talk about this scandal

**Comment by EndermanHackerVN** [comment]
@nkoc6a15 mind you link me the post?

**Comment by nhuvinh** [comment]
What a shame, our tax is wasted. Give us back our money

**Comment by nkoc6a15** [comment]
> @nkoc6a15 mind you link me the post?

https://t.me/adguard_en

**Comment by danglequocbao001** [comment]
And I surprise like "Whao, a big production project come from Vietnamese government finished after 1 or 2 commits on all platfrom like IOS, Android, Window, Linux without folked, credited and edit the server" =))
